### PR TITLE
Update mix.exs to remove compiler warnings

### LINKED ISSUE #2: Compiler warnings with fresh install
I just installed the library and am receiving the following warnings from the compiler:
```
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  .../deps/phoenix_html_sanitizer/mix.exs:20: PhoenixHtmlSanitizer.Mixfile.project/0
```
```
warning: Phoenix.HTML.raw/1 defined in application :phoenix_html is used by the current application but the current application does not depend on :phoenix_html. To fix this, you must do one of:

  1. If :phoenix_html is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix_html is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix_html, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.HTML]]] to your "def project" in mix.exs

Found at 4 locations:
  lib/phoenix_html_sanitizer/helpers.ex:11: PhoenixHtmlSanitizer.Helpers.sanitize/2
  lib/phoenix_html_sanitizer/helpers.ex:17: PhoenixHtmlSanitizer.Helpers.sanitize/2
  lib/phoenix_html_sanitizer/helpers.ex:23: PhoenixHtmlSanitizer.Helpers.sanitize/2
  lib/phoenix_html_sanitizer/helpers.ex:29: PhoenixHtmlSanitizer.Helpers.sanitize/2
```

### PR DESCRIPTION
**Pull request by APB9785**
Resolve #2

### CODE REVIEW

**Comment by rrrene** [comment]
Hi,

this is a package published on Hex, Elixir's package manager.

It is not feasible for a package with a distinct version number to reference the GitHub repo as a dependency.

Have you tried changing the dep to

```
{:html_sanitize_ex, "~> 1.4"}
```

?

**Comment by APB9785** [comment]
Oh, I'm so sorry, I forgot this PR was still open.  I didn't intend for these recent changes to be merged - they were just for my own fork I've been using.  Please disregard!

**Comment by APB9785** [comment]
Actually, since the relevant issue is still open, I've changed the dependency to 1.4 in case you were interested in merging.

**Comment by APB9785** [comment]
I guess I'll go ahead and close this PR again because it doesn't seem to be going anywhere... And it's only 5 LOC anyway.

**Pull request closed without merging**
